---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

inputs:
  - name: merged-stack

outputs:
  - name: image

caches:
  - path: /root/.m2/repository

run:
  path: /bin/sh
  args:
    - '-exc'
    - |
      apk add --quiet --no-progress maven
      mvn --version
      cd merged-stack/my-app
      mvn -q deploy -Dregistry=${REGISTRY} -Dtoken=${TOKEN}
